spring:
 application:
  name: chinese-learning-api
 datasource:
  url: jdbc:postgresql://localhost:5432/chinese_learning_db
  username: postgres
  password: Sakda119
 jpa:
  hibernate:
   ddl-auto: update

  show-sql: true
  
  properties:
   hibernate:
    format_sql: true
jwt:
 secret: MySuperSecretKeyForChineseLearningApplication2026MySuperSecretKey
 expiration: 86400000
 
app:
 upload:
  audio-dir: uploads/audio
  image-dir: uploads/images
telegram:
 bot-token: 8933476984:AAF2FmUwXfCx4LhqaCoiEjE0mQj_HE4oxTU
 public-channel-id: "@studifypublicchannel"
 premium-channel-id: '-1003912067074'
 
 admin-contact: '@SAKDA_chan'
 public-channel-link: "https://t.me/studifypublicchannel"
 premium-channel-link: "https://t.me/+Z1tH3u_7U-c1YWZl"
 