spring:
 application:
  name: chinese-learning-api
 datasource:
  url: jdbc:postgresql://localhost:5432/chinese_learning_db
  username: postgres
  password: Sakda119
 jpa:
  hibernate:
   ddl-auto: update

  show-sql: true
  
  properties:
   hibernate:
    format_sql: true
jwt:
 secret: MySuperSecretKeyForChineseLearningApplication2026MySuperSecretKey
 expiration: 86400000
 
app:
 upload:
  audio-dir: uploads/audio
  image-dir: uploads/images
telegram:
 bot-token: 8933476984:AAF2FmUwXfCx4LhqaCoiEjE0mQj_HE4oxTU
 channel-id: "@studifypublicchannel"
 group-id: "-1004410977989"