spring:
 application:
  name: chinese-learning-api
 datasource:
  url: jdbc:postgresql://localhost:5432/chinese_learning_db
  username: postgres
  password: Sakda119
 jpa:
  hibernate:
   ddl-auto: update

  show-sql: true
  
  properties:
   hibernate:
    format_sql: true